import { execSync } from "node:child_process";
import mdx from "@mdx-js/rollup";
import tailwindcss from "@tailwindcss/vite";
import { voidReact } from "@void/react/plugin";
import { defineConfig } from "vite-plus";
import { voidPlugin } from "void";
import mdxOptions from "void-blog/mdx";
import { voidBlog } from "void-blog/vite";
import blogConfig from "./blog.config.ts";

const optimizedDeps = [
  "@nkzw/stack",
  "@void/react",
  "react",
  "react-dom",
  "react-error-boundary",
  "react/jsx-dev-runtime",
  "react/jsx-runtime",
  "void/pages-client",
  "void/pages-prefetch",
  "void-blog/react",
];

const legacyIgnorePatterns = [
  "node_modules",
  "dist",
  ".wrangler",
  ".void",
  "public",
  "blog",
  "blog.bak",
  "legacy.bak",
  "MOVE",
  "movement.js",
  "max_new_space_size",
  "libuv",
  "*.html",
  "*.htm",
  "*.bak",
  "*.swf",
  "*.mp3",
  "*.png",
  "*.bash",
  "atom-apps-list.md",
  "build.js",
  "cmd.md",
  "cnode-mv.md",
  "dat.json",
  "encodeURIComponent_attack.js",
  "gfw.md",
  "github-proxy.md",
  "index.md",
  "love.md",
  "mac.md",
  "mx-2013.md",
  "nae-cli.md",
  "node-v8-flags.md",
  "optimized-test.js",
  "password.md",
  "pipe.js",
  "server.js",
  "simplehttpserver.js",
  "storyjs-embed.js",
  "timeline.js",
  "timeline.css",
  "urlparse_0.6_0.8.js",
  "visa.md",
  "wedding-net4.md",
  ".jshintrc",
  "mvn-install.sh",
];

function buildCommit() {
  try {
    return execSync("git rev-parse --short HEAD", { encoding: "utf8" }).trim();
  } catch {
    return process.env.GITHUB_SHA?.slice(0, 7) ?? "dev";
  }
}

function buildTime() {
  const formatted = new Intl.DateTimeFormat("sv-SE", {
    dateStyle: "short",
    timeStyle: "short",
    timeZone: "Asia/Shanghai",
  }).format(new Date());
  return `${formatted} (UTC+8)`;
}

export default defineConfig({
  run: {
    tasks: {
      // Cacheable vp check. Type-aware linting reads the .void type
      // declarations that the build generates, hence dependsOn. Inputs cover
      // everything vp check formats, lints, or type-checks; generated files
      // are excluded (their sources are tracked), and .void/dev-trigger-token
      // is a random per-checkout value that would poison the fingerprint.
      check: {
        command: "vp check",
        dependsOn: ["build"],
        env: [],
        input: [
          ".github/**",
          ".void/**",
          "!.void/dev-trigger-token",
          "AGENTS.md",
          "CLAUDE.md",
          "README.md",
          "blog.config.ts",
          "env.d.ts",
          "middleware/**",
          "package.json",
          "pages/**",
          "!pages/posts/**",
          "pnpm-lock.yaml",
          "pnpm-workspace.yaml",
          "posts/**",
          "src/**",
          "!src/redirects.generated.ts",
          "tsconfig.json",
          "vite.config.ts",
          "vitest.config.ts",
          "void.json",
        ],
      },
      // Cacheable build task for CI (the test job restores
      // node_modules/.vite/task-cache and runs `vp run build`). There is
      // deliberately no `build` script in package.json: a task may not shadow
      // a script of the same name, and void deploy falls back to the
      // equivalent `vite build` when the script is absent, so deploy builds
      // never use this cache and always get a fresh commit stamp.
      build: {
        command: "vp build",
        // No env fingerprinting: the build enumerates process.env (void env
        // filtering), which would otherwise fingerprint per-run CI variables
        // like ACTIONS_ORCHESTRATION_ID and invalidate every run.
        env: [],
        // Explicit inputs (no auto tracking): fspy-recorded directory entries
        // for generated dirs (.void) invalidate on every fresh checkout even
        // when excluded. Dependency changes are covered by pnpm-lock.yaml.
        input: [
          "blog.config.ts",
          "env.d.ts",
          "middleware/**",
          "package.json",
          "pages/**",
          "!pages/posts/**",
          "pnpm-lock.yaml",
          "pnpm-workspace.yaml",
          "posts/**",
          "public/**",
          "!public/feed.xml",
          "!public/og/**",
          "!public/sitemap.xml",
          "src/**",
          "!src/redirects.generated.ts",
          "tsconfig.json",
          "vite.config.ts",
          "void.json",
        ],
      },
    },
  },
  define: {
    __BUILD_COMMIT__: JSON.stringify(buildCommit()),
    __BUILD_TIME__: JSON.stringify(buildTime()),
  },
  staged: {
    "*": "vp check --fix",
  },
  // "pages/posts" is generated by voidBlog on every build/check; never format or lint it.
  fmt: { ignorePatterns: [...legacyIgnorePatterns, "pages/posts"] },
  lint: {
    options: { typeAware: true, typeCheck: true },
    ignorePatterns: [...legacyIgnorePatterns, "pages/posts"],
  },
  optimizeDeps: {
    include: optimizedDeps,
  },
  // Lets `vp preview` accept a spoofed Host header to test the canonical-host
  // redirect middleware locally.
  preview: {
    allowedHosts: ["fengmk2.void.app"],
  },
  plugins: [
    voidBlog(blogConfig, { routes: { post: "src/blog/PostRoute.tsx" } }),
    ...voidPlugin(),
    mdx(mdxOptions),
    ...tailwindcss(),
    ...voidReact({
      prefetch: { hoverDelay: 150 },
      viewTransitions: true,
    }),
  ],
  resolve: {
    dedupe: ["react", "react-dom"],
  },
  ssr: {
    optimizeDeps: {
      include: optimizedDeps,
    },
  },
});
